リファクタリング
okoge-kaz/smart-senkyo-extensions pull request #53
Opened 2022-12-02 13:32 UTC by okoge-kaz

## Description

作業が多岐にわたるため、列挙形式とする。

1. Linter flake8 max-line-lengthをblackの設定に合わせた
2. 実行時のディレクトリに依らない実装に変更した
3. Linterのエラーが出ていた箇所を修正
4. unit testを追加

## Related Issues

関連するIssueなし

## What users will see

開発者向け変更なのでなし

## What users will not see

開発者向け変更なのでなし

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Add Test Script

## How Has This Been Tested?

ローカル環境での実行テスト, 自動テストにより

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

## For Reviewers

特になし

2022-12-02 16:32 UTC, Shimo-1999 requested changes

2022-12-02 16:32 UTC, Shimo-1999 commented on src/utils/os/input.py
>          raise (ValueError("入力ファイルが多すぎます: 一度に入力できるファイル数は" + str(MAX_FILE_NUMBER) + "個までです"))
今回の PR とは全く関係ないのですが、ファイル数がちょうど MAX_FILE_NUMBER 個のときにエラーになりそうです。30 行目の `＝` が無いべきなのではないかという指摘です。

2022-12-03 00:56 UTC, Shimo-1999 commented on src/main.py
`create_output_csv_data` と `create_output_xlsx_data` は関数の名前が似ている（拡張子の違いのみである）ので、3 つ目の引数に統一感があると見やすい気がしていてます。

1. `create_output_csv_data` の引数に、変更前のように出力先の debug フォルダを明示する。
2. `create_output_xlsx_data` の引数も `folder_name` のみにする。（関数の中で output フォルダに格納する処理をする。）
3. `create_output_csv_data` という関数名ではなく `create_debug_csv_data` などに変更し、`create_output_xlsx_data` とは別の性質の関数であることを示す。

のどれかをすると、読みやすいと思います。

2022-12-03 01:00 UTC, Shimo-1999 commented on src/main.py
>      create_output_xlsx_data(smart_senkyo_formatted_data_list, INPUT_FILE_NAME_LIST, "/output/formatted_output")
`create_output_csv_data` と `create_output_xlsx_data` は関数の名前が似ている（拡張子の違いのみ）ので、3 つ目の引数に統一感があると見やすい気がしていてます。

1. `create_output_csv_data` の引数に、変更前のように出力先の debug フォルダを明示する。
2. `create_output_xlsx_data` の引数も `folder_name` のみにする。（関数の中で output フォルダに格納する処理をする。）
3. `create_output_csv_data` という関数名ではなく `create_debug_csv_data` などに変更し、`create_output_xlsx_data` とは別の性質の関数であることを示す。

のどれかをすると、読みやすいと思います。

2022-12-03 01:48 UTC, okoge-kaz commented on tests/app/utils/preprocess/pre/test_convert_full_width_number_to_half_width_number.py
> +        ]
修正しました。

2022-12-03 04:46 UTC, okoge-kaz commented on src/utils/os/input.py
>          raise (ValueError("入力ファイルが多すぎます: 一度に入力できるファイル数は" + str(MAX_FILE_NUMBER) + "個までです"))
おっしゃる通りだと思います。修正しました

2022-12-03 04:46 UTC, okoge-kaz commented on src/main.py
>      create_output_xlsx_data(smart_senkyo_formatted_data_list, INPUT_FILE_NAME_LIST, "/output/formatted_output")
```python
    if "--debug" in argv:
        # Excelだとデバッグが難しいのでCSVデータも出力するようにするDebugモード
        create_debug_csv_data(smart_senkyo_formatted_data_list, INPUT_FILE_NAME_LIST, "formatted_output")
        create_debug_csv_data(not_converted_data_list, INPUT_FILE_NAME_LIST, "not_converted_output")

    # for output
    create_output_xlsx_data(smart_senkyo_formatted_data_list, INPUT_FILE_NAME_LIST, "formatted_output")
    create_output_xlsx_data(not_converted_data_list, INPUT_FILE_NAME_LIST, "not_converted_output")
```
となるように修正しました

2022-12-03 06:52 UTC, Shimo-1999 commented on src/app/address_separator/utils/extract/detail/check/data_check.py
> +        splitted_address_data_dictionaries["error1"] += "ERROR: address1の列の情報が不正です。自動整形過程で何らかの問題が発生しました。  "
18 行目の `if` は `elif` の間違いですか？
16 行目の `if` の後に `pass` をしていますが、意味のない処理になってしまっています。

2022-12-03 07:12 UTC, Shimo-1999 commented on src/app/address_separator/utils/extract/district.py
> +    non_town_address_data = non_town_address_data_list
（git Lens を見る限り、切り出したブランチでの変更で、藤井さんの作業部分ではなく本当に申し訳ないのですが、）
引数を `non_town_address_data` にし、18 行目を削除した方がいいと思います。
それに合わせて、10 行目の docstring の引数の型も `list[str]` から `str` に変えた方が良さそうです。

2022-12-03 07:25 UTC, Shimo-1999 commented on src/app/address_separator/utils/extract/town.py
> +        town_address = address[0:FIRST_NUMBER_APPEAR_INDEX]
`: str` は、あった方が良いと思いましたが、`: str` をつけると、`mypy` で `Name "town_address" already defined on line 38` というエラーが出ますね。なるほどです。

2022-12-03 07:30 UTC, Shimo-1999 commented on src/app/address_separator/utils/extract/town.py
> +    town_address_data = non_city_address_data
（git Lens を見る限り、切り出したブランチでの変更で、藤井さんの作業部分ではなく本当に申し訳ないのですが、）
引数を town_address_data にし、58 行目を削除した方がいいと思います。

2022-12-03 07:39 UTC, Shimo-1999 commented on src/app/address_separator/utils/preprocess/post/fix_special_name_address.py
> +                if "0" <= address[id - 1] and address[id - 1] <= "9" and address[id + 1] >= "0" and address[id + 1] <= "9":
細かいところで、個人の主義や趣味の範囲かもしれませんが
```
if address[id] == "の" and 0 < id <= len(address):
                if "0" <= address[id - 1] <= "9" and "0" <= address[id + 1] <= "9":
```
でも同じ分岐ができそうで、こっちの方が好きです。

2022-12-03 07:58 UTC, okoge-kaz commented on src/app/address_separator/utils/extract/detail/check/data_check.py
> +        splitted_address_data_dictionaries["error1"] += "ERROR: address1の列の情報が不正です。自動整形過程で何らかの問題が発生しました。  "
指摘ありがとうございます。
修正しました

2022-12-03 08:00 UTC, okoge-kaz commented on src/app/address_separator/utils/extract/district.py
> +    non_town_address_data = non_town_address_data_list
Pull Requestの題名をリファクタリングにした私が悪いのですが、今回の主題はあくまでもCIの整備のためのリファクタリングであって、下山田さんや、城戸さんが行っているリファクタリングとは趣旨が異なります。

2022-12-03 08:05 UTC, okoge-kaz commented on src/app/address_separator/utils/extract/district.py
> +    non_town_address_data = non_town_address_data_list
```python3
def extract_district(non_town_address: str) -> tuple[str, str]:
    """
    extract district: 市区町村を抽出する(prefecture, city, townによって除かれたデータのうち数字が出現するまでのデータをとる)

    Parameters
    ----------
    non_town_address : str
        都道府県を抽出した残りの住所データ

    Returns
    -------

    """

    district, other = pull_out_district_field(non_town_address)

    return district, other
```
のように修正しました

2022-12-03 08:08 UTC, Shimo-1999 commented on src/app/address_separator/utils/extract/district.py
> +    non_town_address_data = non_town_address_data_list
はい。しかし、今回の PR 先が main ブランチに切り替わっていたので、私と城戸の変更も main ブランチに反映されてしまうと思い指摘することにしました。

2022-12-03 08:09 UTC, okoge-kaz commented on src/app/address_separator/utils/extract/town.py
> +    town_address_data = non_city_address_data
```python
def extract_town(address_after_city: str) -> tuple[str, str]:
    """
    市町村よりさらに細かな地区行政区分を文字列から取得する
    """
    towns: str = ""
    non_town_address_data: str = ""

    FIRST_NUMBER_APPEAR_INDEX: int = 100000  # 住所文字列よりも明らかに大きな値
    # 連続した小文字のアルファベットを検索する
    match_number = re.search("[0-9]+", address_after_city)
    if match_number:
        FIRST_NUMBER_APPEAR_INDEX = match_number.start()  # マッチした文字列の開始位置： 3

    if have_administrative_division_name(address_after_city, ["区", "郡", "町", "村"]):
        town_address: str = ""
        non_town_address: str = ""

        if "区" in address_after_city:
            town_address, non_town_address = split_address_into_town_and_non_town("区", address_after_city, FIRST_NUMBER_APPEAR_INDEX)

        elif "郡" in address_after_city:
            town_address, non_town_address = split_address_into_town_and_non_town("郡", address_after_city, FIRST_NUMBER_APPEAR_INDEX)

        elif "町" in address_after_city:
            town_address, non_town_address = split_address_into_town_and_non_town("町", address_after_city, FIRST_NUMBER_APPEAR_INDEX)

        elif "村" in address_after_city:
            town_address, non_town_address = split_address_into_town_and_non_town("村", address_after_city, FIRST_NUMBER_APPEAR_INDEX)

        towns = town_address
        non_town_address_data = non_town_address

    else:  # 区、郡、町、村 が town_address_dataに存在しないとき
        towns = ""
        non_town_address_data = address_after_city

    return (towns, non_town_address_data)
```

Done

2022-12-03 08:14 UTC, okoge-kaz commented on src/app/address_separator/utils/preprocess/post/fix_special_name_address.py
> +                if "0" <= address[id - 1] and address[id - 1] <= "9" and address[id + 1] >= "0" and address[id + 1] <= "9":
```python
if "0" <= address[id - 1] <= "9" and "0" <= address[id + 1] <= "9":
```
に関しては、そのとおりかと

2022-12-03 08:16 UTC, okoge-kaz commented on src/app/address_separator/utils/preprocess/post/fix_special_name_address.py
> +                if "0" <= address[id - 1] and address[id - 1] <= "9" and address[id + 1] >= "0" and address[id + 1] <= "9":
そもそも論として、if 文を直書きで連ねている事自体が問題なのですが、今回の変更趣旨とは異なるため放置しています

2022-12-03 10:20 UTC, Shimo-1999 commented on tests/app/utils/preprocess/pre/test_convert_full_width_number_to_half_width_number.py
> +        ]
漢字の隣の 1 には全角チェックが働いてなくて見づらいですが、8 行目と 11 行目、10 行目と 14 行目が同じテストをしているように見えます。
<img width="200" alt="スクリーンショット 2022-12-03 19 17 45" src="https://user-images.githubusercontent.com/63487964/205436046-87dc6ae6-346f-476a-929c-3cc4134956ce.png">

2022-12-03 10:24 UTC, Shimo-1999 commented
ここ以外は全て問題ないと思いました。

2022-12-03 10:47 UTC, okoge-kaz commented on tests/app/utils/preprocess/pre/test_convert_full_width_number_to_half_width_number.py
> +        ]
何度もすみません。
修正します

2022-12-03 11:22 UTC, Shimo-1999 approved these changes

2022-12-03 11:25 UTC, merged