Feature/support for v2 format
okoge-kaz/smart-senkyo-extensions pull request #54
Opened 2022-12-14 16:10 UTC by haruboring

## Description

スマート選挙がversion2に移行したために求める整形後の名簿の形式に変更があった。([v2フォーマット](https://docs.google.com/spreadsheets/d/1uqUyE9q2Yybd1Ue1ePpXdATlLg_2k3_iAUXrQixX9ZY/edit#gid=300869304))
よってそれに対応するために大規模なコードの変更を行なった。
依頼のDM->[Slack](https://senkyo-inc.slack.com/archives/C04DBGFJLQ0/p1669598524286749)
[TechInternTask](https://www.notion.so/Tech-Intern-8d61d83bf91148be811cf27c436010df?p=4a613c80d05b4b9ba7c7a2d8e5a7baeb&pm=s)

## Overview of Changes

- **v2フォーマットの形式に対応できるようにコードを大規模に修正**
- 対応列名の修正([対応列名](https://docs.google.com/spreadsheets/d/1mLMNekLOFE60lm02TPsSk2lQ4yvFkGVrK968h4FEQvY/edit#gid=1361753996))
- 複数ファイルの入力に対しても(整形済み組織、整形済み個人、変換できなかったもの)が一つづつまとまるように変更
  - 上記に対応するためtagやタイトルメモについてのフォーマット方法の変更
- サンプルinputファイルの追加
- pytestの修正

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [x] Tests (You added tests for code that already exists, or your new feature included in this PR)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

## For Reviewers

- 名寄せは行っていない

[仕様書](https://www.notion.so/v2-format-mtg-12-02-16-00-17-40-8856e82ed5ca4ceb84081622248008ae)
[対応列名](https://docs.google.com/spreadsheets/d/1mLMNekLOFE60lm02TPsSk2lQ4yvFkGVrK968h4FEQvY/edit#gid=1361753996)

2022-12-16 23:36 UTC, Shimo-1999 requested changes
問題がないと思ったのでロジックについてのコメントはないです。

命名関連の細かめのコメントがあります。
若干自分の好みも含むので、変更するかしないか、変更するとしても今直すかリファクタに回すか、任せます。
また、以下の点は複数箇所あったので全てにはコメントしていないです。
- if ~~~ is False を if not ~~~ にしたい
- one_~~~ の変数名, ~~~_data の変数名を変えたい
- フォルダ作成の際に
```
if not os.path.isdir(DIR_NAME):
    os.makedirs(DIR_NAME)
```
ではなく、
```
os.makedirs(DIR_NAME, exist_ok=True)
```
を使いたい

コメントアウトされた pytest がなぜ自動テストで pass しなかったのは不思議です。

2022-12-16 23:36 UTC, Shimo-1999 commented on tests/test_main.py
> +    #     assert DEBUG_FILES[i].equals(NEW_DEBUG_FILES[i])
このテストが自動テストでなぜ落ちるのか謎ですね...。

2022-12-17 03:54 UTC, haruboring commented on src/interfaces/company/formatted_company_info.py
> +        FormattedCompanyInfo.company_id[not_formatted_company_info.name].append(FormattedCompanyInfo.id)
僕も藤井さんに助けを乞いました....
普通に使用可能な文法を知らないだけだと思うので何とかしてこういう使い方も勉強したいですね...

2022-12-17 03:55 UTC, haruboring commented on .gitignore
> +src/debug/*.xlsx
実装ミスでした....
`src/output/*.xls or xlsx`に変更しておきます

2022-12-17 04:00 UTC, haruboring commented on tests/test_main.py
> +    #     assert DEBUG_FILES[i].equals(NEW_DEBUG_FILES[i])
（当然ですが）`subprocess.run(["python3", "src/main.py", "--debug", "--timer"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=True)`
を1回目のDEBUG_FILESをまとめる前にも行うとpassできるので、手元とテスト環境が違うんでしょうね...

2022-12-17 04:00 UTC, haruboring commented on src/utils/os/output_csv.py
> +        os.makedirs(DIR_NAME)
ありがとうございます。
修正しました

2022-12-17 04:02 UTC, haruboring commented on src/utils/convert/company/convert_formatted_company_info.py
> +            formatted_personal_info: FormattedCompanyInfo = FormattedCompanyInfo(one_person_not_formatted_company_info)
oneを乱用していた過去のコードをコピペしちゃってました...
修正します

2022-12-17 04:06 UTC, haruboring commented on src/interfaces/company/not_formatted_company_info.py
> +        self.company_url: str = check_type(one_person_data[str(company_index) + "company_url"], str)
ありがとうございます！

2022-12-17 04:07 UTC, haruboring commented on src/interfaces/personal/formatted_personal_info.py
> +    def __init__(self, not_formatted_info: NotFormattedPersonalInfo):
変更しました

2022-12-17 04:28 UTC, haruboring commented on src/interfaces/personal/formatted_personal_info.py
> +        return is_existed
@Shimo-1999 
> （常に bool を返すなら get ではない方が良い？）

返り値としては常にboolを返すのですがこの関数のメイン挙動は
`self.introduced_id = str(FormattedPersonalInfo.personal_id[inviter_name][0])`
にあるように情報の取得なんですよね...getは返り値なのでgetよりはfillとかの方が適切なのはそうです

複数機能を一つの関数にまとめてしまっているので命名が難しいです
どう思いますか？

2022-12-17 05:03 UTC, haruboring commented
@Shimo-1999 
if not A
if A is False
はどちらが可読性に優れているか正直わかりませんでした(リーダブルコードを読む時間が取れておらずすいません、今年中には読みます)
リーダブルコード的には何と書かれているかわかりますか？

2022-12-17 05:21 UTC, Shimo-1999 commented on src/interfaces/personal/formatted_personal_info.py
> +        return is_existed
1. 紹介者の import_number が存在するかどうか調べる
2. 紹介者に import_number が複数あれば１つ目を、無ければ、新しい number を割り当てる

の二つの機能ということですよね。

呼び出し側の返り値を意識して、1. の機能を全面に押し出した命名を考え、上記の関数名のような提案をしました。
個人的には、関数名だけで機能を全て説明し切るのは困難なので、docstring で補うのが丸いと思います。（機能のどの部分を関数名にするかは任せます。）

2022-12-17 05:30 UTC, Shimo-1999 commented
> 

該当箇所がすぐには見つかりませんでした（そもそも条件式の not の可読性については書いていないかもしれないです。）
A の部分に　is_~~~ というような変数が入るとすると、一行に is が二回登場して嫌だなくらいの気持ちで書きました。

2022-12-17 05:31 UTC, haruboring commented on src/interfaces/personal/formatted_personal_info.py
> +        return is_existed
個人的に2が重要だと考えているので命名をget->fillに変更するだけにしておきます。
次のリファクタの時に関数を分離したり等して読みやすくしていただけると！

2022-12-17 05:36 UTC, haruboring commented
@Shimo-1999 
たしかにis_A isは気持ち悪いですかね...
ちょっと判断が難しいので今回はこのままにしておきます🙇‍♀️(is Falseの方が視覚的に読みやすい可能性もあるので...)
修正全て完了しました。確認ののち承認いただけるとありがたいです

2022-12-17 05:38 UTC, haruboring commented
@Shimo-1999 
昨日、仕様の微小な変更に伴い出力結果も多少変わっているので再度出力結果を確認して整合性が取れているか確認していただけると助かります。(私も確認作業行います)

2022-12-17 05:40 UTC, Shimo-1999 approved these changes

2022-12-17 05:43 UTC, Shimo-1999 commented
すみません、先走って approve に変更してしまいましたが、出力ファイルは今から確認します。

2022-12-17 05:55 UTC, Shimo-1999 commented
組織名のカラムの欄などもふくめて、正しい挙動をしているようです。

テストファイルの作成をミスっていて、sample3 の 3company_name の欄に住所が入っていることに気がつきました....

2022-12-17 05:57 UTC, haruboring commented
@Shimo-1999 
大丈夫そうですね...
一応inputファイルの修正お願いします！
修正終わって伊藤さんからのSlackの返事きたらマージします
ありがとうございました！めちゃめちゃ助かりました！

2022-12-17 06:05 UTC, Shimo-1999 commented
sample3  を修正し、debug csv も更新しました。

2022-12-17 07:16 UTC, merged