Hotfix/modify specifications of inviter
okoge-kaz/smart-senkyo-extensions pull request #57
Opened 2022-12-22 08:07 UTC by haruboring

## Description

[こちら](https://www.notion.so/V2-6236d55269814db0a53a24c8c017af7d)の修正（超絶高）への対応
> 修正（超絶高）（対応中）
紹介者を個人の中から探す上で、重複がいた場合紐付けずに重複しているその名前を入れる現状：重複していたら一番上の人と紐づく

軽微なリファクタリング

## Overview of Changes

- 紹介者が一意に定まらない(紹介者として指名されている名前が複数人いる)時は、`inviter_id`を紹介者の名前にし、該当の紹介者の紹介元リストに`?`を入力する
- 不必要なimport文、コメントの削除
- クラスメソッドの並び替え

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

## For Reviewers

2022-12-22 08:25 UTC, Shimo-1999 requested changes

2022-12-22 08:25 UTC, Shimo-1999 commented on src/interfaces/company/formatted_company_info.py
> +
メソッドの順番について、そのクラスが呼び出された時に一番初めに動く `__init__()` が `class` のすぐ下にあるべきで、それ以外のメソッドはそれより下に書くものだと思っていました。（が、これは偏見かもしれないです。）

例えば、
```
class FormattedCompanyInfo:

    def __init__():

    @classmethod
    def increment_id(cls):
    
    @classmethod
    def get_company_id():
```

というように順番で書くものだと思っていました。（が、間違っているかもしれません。）

`@classmethod` を続きで書くことには賛成ですが、`__init__ ()`を先に持って来たい気持ちになっています。
どう思いますか？

2022-12-22 08:38 UTC, okoge-kaz requested changes

2022-12-22 08:38 UTC, okoge-kaz commented on src/interfaces/personal/formatted_personal_info.py
> +        # 現時点では無加工
TODOではないようなので冗長です。
将来あるかも...という場合は、そのときにしてください

2022-12-22 08:40 UTC, okoge-kaz commented on src/interfaces/company/formatted_company_info.py
> +
横からすみません
一般的にインスタンスメソッド -> クラスメソッドの順番に書くという暗黙ルールはあると思いますが、コンストラクタが一番上にするというルールはない気がします

2022-12-22 09:12 UTC, Shimo-1999 commented on src/interfaces/company/formatted_company_info.py
> +
なるほどです。やはり、偏見混じりの意見だったようです。
ありがとうございます。

2022-12-22 09:47 UTC, haruboring commented on src/interfaces/personal/formatted_personal_info.py
> +        # 現時点では無加工
@okoge-kaz 
`# 現時点では無加工`を削除しておきます

2022-12-22 09:48 UTC, haruboring commented on src/interfaces/company/formatted_company_info.py
> +
ありがとうございます。
とりあえずこのままにさせていただきます

2022-12-22 10:17 UTC, Shimo-1999 commented on src/interfaces/company/formatted_company_info.py
> +
今回の場合は __init__() はインスタンスメソッドに当たると思うので、藤井さんの意見に従うとクラスメソッドより先に書くべきではないですか？（私のインスタンスメソッドの理解が間違っていますか？）

あえてそれに反する理由がないなら、変更するべきだと思います。

2022-12-22 10:20 UTC, okoge-kaz commented on src/interfaces/company/formatted_company_info.py
> +
< 偏見混じりの意見
別に偏見というほどではないですよ。明文化されたルールを聞かないなというぐらいですね

2022-12-22 10:24 UTC, okoge-kaz commented on src/interfaces/company/formatted_company_info.py
> +
> 私のインスタンスメソッドの理解が間違っていますか？

間違ってないです。
城戸さんの修正し忘れかと

2022-12-22 13:23 UTC, haruboring commented on src/interfaces/company/formatted_company_info.py
> +
@Shimo-1999 , @okoge-kaz 
申し訳ありません修正しました！

2022-12-22 17:58 UTC, Shimo-1999 approved these changes

2022-12-22 23:46 UTC, okoge-kaz approved these changes

2022-12-22 23:56 UTC, okoge-kaz requested changes
修正をした意図が不明なため、レビュアーに不親切です。
また、修正忘れが目立ちます

2022-12-22 23:56 UTC, okoge-kaz commented on src/interfaces/personal/formatted_personal_info.py
> +
インスタンスメソッド -> クラスメソッドの順番にしてください。
`def fill_introduced_id(self) -> bool`は、インスタンスメソッドですよね？
それと、booleanが返り値な場合は、`is〜`のような命名が望ましいです。`fill_instroduced_id`（紹介者IDを埋める）がboolを返すのはかなり非直感的ですので

2022-12-22 23:56 UTC, okoge-kaz commented on src/utils/convert/convert_not_formatted_info.py
>      DataFrameを行ごとに1人の個人データとして NotFormattedPersonalInfo 型に変換する。
説明文が `NotFormattedPersonalInfo`のままですね...

2022-12-22 23:56 UTC, okoge-kaz commented on src/main.py
> +    not_formatted_personal_info_array, not_formatted_company_info_array = convert_DataFrame_to_NotFormattedInfo(not_formatted_integrated_data)
変えた意図を知らないので、どこに書いて頂けると 🙏

2022-12-22 23:56 UTC, okoge-kaz commented on src/interfaces/utils/memo/separate_company_tel_and_memo.py
> -    return separated_company_tel, memo_text
削除理由がわからないので書いてください

2022-12-23 02:43 UTC, haruboring commented on src/utils/convert/convert_not_formatted_info.py
>      DataFrameを行ごとに1人の個人データとして NotFormattedPersonalInfo 型に変換する。
対応しました

2022-12-23 02:53 UTC, haruboring commented on src/interfaces/personal/formatted_personal_info.py
> +
@okoge-kaz 
introduced_idを埋めるのと、boolを返すという二つの機能があったので分割して、`is_inviter_exist`と、`fill_is_inviter`の二つのメソッドに分離したら、
`src/utils/convert/personal/convert_formatted_personal_info.py`で

```
# 紹介者を追加する。ただし、紹介者として名簿に存在しない人物が指名された場合、新たにその紹介元の名前だけの名簿を作る。
    for formatted_personal_info in formatted_personal_info_array:
        is_existed: bool = formatted_personal_info.is_inviter_exist()
```
になって、`is_inviter_exist`の中身をみないと、紹介者が追加されているかわからないので、


関数名を`is_inviter_exist_and_fill_introduced_id`として二つの機能を全面に出してみました。

どうでしょうか...

2022-12-23 03:24 UTC, haruboring commented on src/interfaces/personal/formatted_personal_info.py
> +
一関数で一つの役割<関数名による可読性の向上
だと判断しました。
2つの役割と言ってもifで分岐しているだけなのでギリギリ大丈夫かなと...

2022-12-23 03:29 UTC, okoge-kaz commented on src/interfaces/personal/formatted_personal_info.py
> +
そのような関数名は、望ましくないです。

そもそも、埋める機能と存在確認を一つの関数で行うという発想をやめてください。

2022-12-23 03:31 UTC, okoge-kaz commented on src/interfaces/personal/formatted_personal_info.py
> +
むしろ〈分離したら〜〉の箇所の結果が、問題な理由がわかりません。

何か問題があるのでしょうか？

2022-12-23 03:38 UTC, haruboring commented on src/interfaces/personal/formatted_personal_info.py
> +
`src/utils/convert/personal/convert_formatted_personal_info.py`だけをみると、`is_inviter_exist`という関数しか見えず、埋めているかどうかを判断できないのもあまり良くないかなと思いました。
一つの関数で一つの機能を持つ必要性は理解しているつもりでしたが、もう少し重要性を感じ取るべきでした。
分離したいと思います。

2022-12-23 03:42 UTC, okoge-kaz commented on src/interfaces/personal/formatted_personal_info.py
> +
もしも複数のことをするなら、それだけの抽象度をもった関数、メソッドにするべきですね。

2022-12-23 03:42 UTC, okoge-kaz commented on src/interfaces/personal/formatted_personal_info.py
> +
個々の細かい処理をまとめて、前処理と言えるなら、それは前処理という一つの責務しか負っていないと言えるので

2022-12-23 09:11 UTC, okoge-kaz requested changes

2022-12-23 09:11 UTC, okoge-kaz commented on src/interfaces/personal/formatted_personal_info.py
> +    def fill_introduced_id(self, is_existed: bool) -> None:
is_existedという引数名はやめてください。
より詳細にお願いします。

2022-12-23 09:11 UTC, okoge-kaz commented on src/interfaces/personal/formatted_personal_info.py
> +            if len(FormattedPersonalInfo.personal_id[inviter_name]) == 1:
== 1のときのみの処理なのですか？
意図が分かりかねます。(できればprivateな関数を作って切り出していただけると)

2022-12-23 09:11 UTC, okoge-kaz commented on src/interfaces/personal/formatted_personal_info.py
> +                self.introduced_id = inviter_name
idにnameを代入するのは本当に想定ですか？
もしそうなのであれば、何かしらの注意書きをお願いします。
正直、訳がわかりません

2022-12-23 09:11 UTC, okoge-kaz commented on src/interfaces/personal/formatted_personal_info.py
> +        if inviter_name == "":
このpassする書き方どうにかできませんか？
(条件は、変更したいもので書きてください)

2022-12-23 11:06 UTC, haruboring commented on src/interfaces/personal/formatted_personal_info.py
> +                self.introduced_id = inviter_name
仕様らしいです...
同一人物がいる際に手動でどちらが正解の人物かを判断するらしいので、番号でなく名前にしてもらうらしいです。
一応pydocsに書いてるのですが、直前にもコメントアウトを追加しておきます

2022-12-23 11:15 UTC, haruboring commented on src/interfaces/personal/formatted_personal_info.py
> +    def fill_introduced_id(self, is_existed: bool) -> None:
is_inviter_existed_in_roster
に変更しました

2022-12-23 11:20 UTC, haruboring commented on src/interfaces/personal/formatted_personal_info.py
> +        if inviter_name == "":
変更しました

2022-12-23 11:26 UTC, haruboring commented on src/interfaces/personal/formatted_personal_info.py
> +            if len(FormattedPersonalInfo.personal_id[inviter_name]) == 1:
@okoge-kaz 
すいません。どの部分をprivateメソッドとして切り出せば良いでしょうか？
結構短いコードなのでどこかを切り抜いても
```
def __fill_˜(self):
    # 原稿のfill_introduced_idの中身とほぼ一緒


def fill_introduced_id():
    self.introduced_id = __fill_˜(self):
```

になる気がしてしまうのですが...

2022-12-24 02:58 UTC, okoge-kaz approved these changes
指摘した点を修正したら :LGTM:

2022-12-24 02:58 UTC, okoge-kaz commented on src/interfaces/personal/formatted_personal_info.py
> +    # 紹介者のidを検索する時のためにkey:名前, value:personal_idの辞書をつくる
`key:名前`について、私も誤解した点なのでもう少し詳しくお願いします
（細かいですが）

2022-12-24 02:58 UTC, okoge-kaz commented on src/interfaces/personal/formatted_personal_info.py
> +        if (not_formatted_personal_info.full_name in FormattedPersonalInfo.personal_ids_by_personal_name) is False:
```suggestion
        if (not_formatted_personal_info.full_name in FormattedPersonalInfo.personal_ids_by_personal_name.keys()) is False:
```
このようにしたほうが良いかと

2022-12-24 07:17 UTC, merged